#!/bin/bash -ex
# executed after apply-overlay

################################################################################
# TKL generic install function
################################################################################
cwd=$(dirname $0)
source $cwd/functions

################################################################################
# Set appliance hostname
################################################################################
HOSTNAME=silverstripe
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts
hostname silverstripe

################################################################################
# Start required services
################################################################################
#/etc/init.d/mysql start
#/etc/init.d/apache2 start

################################################################################
# Silverstripe pre-configured MySQL database
# Notes: 
################################################################################
cd /usr/local/silverstripe/
mysqladmin -h 127.0.0.1 -uroot --password=adminpass CREATE silverstripe
mysql -h 127.0.0.1 -uroot --password=adminpass silverstripe < silverstripe245.sql
echo "CREATE USER 'ssdbuser'@'localhost' IDENTIFIED BY 'ssdbuserpass'" | mysql -h 127.0.0.1 -uroot --password=adminpass
echo "GRANT ALL PRIVILEGES ON silverstripe.* TO 'ssdbuser'@'localhost'" | mysql -h 127.0.0.1 -uroot --password=adminpass

################################################################################
# Install required packages for Silverstripe
################################################################################
apt-get update
install php-pear php5-cli php5-gd

################################################################################
# Install Silverstripe
################################################################################
cd /usr/local/silverstripe/
wget http://www.silverstripe.org/assets/downloads/SilverStripe-v2.4.5.tar.gz
tar -zxvf SilverStripe-v2.4.5.tar.gz
rm -f SilverStripe-v2.4.5/install.php
cp -frv SilverStripe-v2.4.5/* /var/www/silverstripe/
cp -frv SilverStripe-v2.4.5/.htaccess /var/www/silverstripe/
cp -frv _config.php /var/www/silverstripe/mysite/

################################################################################
# Stop services
################################################################################
#/etc/init.d/mysql stop
#/etc/init.d/apache2 stop
