#!/bin/bash -e
# Based on Psiphon TKLPatch

################################################################################
# set Silverstripe MySQL DB user password
################################################################################
. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/silverstripe-db-passwd

